# Generated by Django 4.1.4 on 2022-12-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(upload_to='user'),
        ),
    ]
