# Generated by Django 4.1.4 on 2022-12-28 04:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apps.customuser')),
            ],
        ),
    ]
