# Generated by Django 4.1.4 on 2022-12-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='u_firstname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='u_image',
            field=models.ImageField(default='default/avatar.jpg', upload_to='user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='u_lastname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
