# Generated by Django 4.1.4 on 2022-12-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_feedback_u_firstname_feedback_u_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='apps.customuser'),
            preserve_default=False,
        ),
    ]
